### PR TITLE
fix install location

### LINKED ISSUE #1: Actionlib-msgs is in lib/python3.7/site-packages
Not sure if this is the correct repo for this but:
`actionlib-msgs` is placed in `/opt/melodic/lib/python3.7/site-packages` while `actionlib` and `actionlib-tutorials` are in `/opt/melodic/lib/python3.8/site-packages`.

`roslaunch` was failing because of ModuleNotFoundError for `actionlib-msgs`. Copying `actionlib-msgs` over to `/opt/melodic/lib/python3.8/site-packages` seems to work but it does not look like a good solution.

### PR DESCRIPTION
**Pull request by acxz**
resolves #1

### CODE REVIEW

**Comment by jwhendy** [comment]
Did you verify that this was the cause? I just rebuilt *everything* ~1 week ago and do not have the packages mentioned in #1 in a 3.7 directory. Mine are in 3.8. So, namely:
- were your packages also in 3.7?
- if so, you verified that these lines in the PKGBUILD caused that, and by removing them the packages went into the 3.8 directory?

**Comment by jwhendy** [comment]
Another thought: if the messages during build pop up like "Ignoring unused variable python blah blah," then this isn't one of the packages that even leverages the python lib make options...

It's not in the [original list of affected packages](https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8), which also makes me suspicious that this was the cause.

**Comment by acxz** [comment]
Yeah ur right I think the issue to that post is a rebuild, but removing the python artifacts is something to do anyway and this will force a rebuild for users as the package number is updated. We should wait to hear back from the user before closing the issue, but I think this PR can go through.

**Review by bionade24 — CHANGES_REQUESTED** [review]
I think the `arch=()` array is wrong again? Is this really pure python code?

**Comment by acxz** [comment]
This is a package that contains message definitions. As such it generates code for messages but does not compile anything. I think arch=() is appropriate.

**Review by bionade24 — APPROVED** [review]

**Pull request merged**
